@Library('github.com/sorah/jenkinsfile-slack@master') _
pipeline {
    agent {
        docker {
            image 'pipeline_agent'
            args '-v /root/.m2:/root/.m2 -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages {
        stage('Test') {
            steps {
                dir('rest_api') {
                    sh "mvn -U test cobertura:cobertura -Dcobertura.report.format=xml"
                }
            }
        }
        stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('sonar') {
                    dir('rest_api') {
                        sh 'mvn sonar:sonar'
                    }
                }
            }
        }
    }
    post {
        always {
            postNotifySlack currentBuild.result
        }
    }
}
