@Library('github.com/sorah/jenkinsfile-slack@master') _
pipeline {
    agent {
        docker {
            image 'maven:3.6.1-jdk-8'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Test') {
            steps {
                dir('rest_api') {
                    sh "mvn -U test"
                }
            }
        }
        stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('sonar') {
                    dir('rest_api') {
                        sh 'mvn sonar:sonar'
                    }
                }
            }
        }
    }
    post {
        always {
            postNotifySlack currentBuild.result
        }
    }
}
